title: Jenson Chan
logo: /assets/img/logo.png
description: 所以我出手了 🌚🆘
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
email: waydxd@outlook.com
linkedin: https://www.linkedin.com/in/jenson-chan-090002256/

# GitHub Pages specific configuration
github : {
  repository_url: "https://github.com/waydxd"
}
url: https://waydxd.github.io
baseurl: ""

spotify_playlist_id: "6OQ5GWZjSEsRYEs7lYbb7m"  # Example Spotify playlist ID; replace with your own if desired